### ISSUE TITLE
Line numbering breaks the linking

### ISSUE THREAD

**Issue by kuliyys** [felix-hilden/sphinx-codeautolink#137] opened 2023-04-17 16:28 UTC
### Issue
When adding `:lineno:` to code-blocks and literalinclude's this breaks the linking and all the links are absent with the compiler giving `Could not resolve` and `Could not match a code example to HTML` errors respectively.

I am sorry, I would like to elaborate, but I cannot understand, how to submit minimal reproducible example. Please tell me, how I can be more helpful in any way.

**Comment by felix-hilden** [comment] 2023-04-17 17:51
Thanks for submitting the issue! Your description was to the point and I think gives most of the information to debug, so don't worry 👍 What is meant by a minimal reproducible example would be a minimal but complete project that when built with Sphinx would produce the error. So in this case most likely just an `index.rst` and a simple `config.py`. For small stuff, just including it in the issue is entirely fine, like so:

```
# index.rst
Example
*******

.. code-block:: python
    :linenos:

    import numpy

# conf.py
extensions = ["sphinx-codeautolink"]
```

**Comment by kuliyys** [comment] 2023-04-26 14:05
Thank you for the detailed answer!
Attached here is my [minimal_reproducible_sample.zip](https://github.com/felix-hilden/sphinx-codeautolink/files/11333717/Minimal_reproducible_sample.zip). Sorry that it took a week to do it, I will respond more quick now.

**Comment by felix-hilden** [comment] 2024-03-14 18:50
Hey! Sorry for dropping this for the longest time. I've now pushed a fix, expect this to be released in the coming days once I've had a look at the other issues. I'll leave this open in the meantime and close it on release so you'll get a notification. In the meantime you can git-install to try it out if you want to!

**Comment by felix-hilden** [comment] 2024-04-17 16:31
Finally, on the 1st anniversary of this ticket, the new version has been published and this can be closed! :P

**Closed by felix-hilden** 2024-04-17 16:31 UTC
Labels: bug
